services:
  apexpredictbackend:
    image: apexpredictbackend
    build:
      context: backend
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 5000:5000
